### PR TITLE
Fixed #394 Tomcat 8 Psi probe not listing global and application datasources

### LINKED ISSUE #394: Support for Tomcat 8
```
What steps will reproduce the problem?
1. I copied the probe.war file into my tomcat apache-tomcat-8.0.0-RC10/webapps 
folder
2. restarted the server
3. Error : No container found for your server

What is the expected result?
Display the page without any error.

What happens instead?
getting below error message, and not able to view the process.

What version of Probe are you using?
PSI Probe 2.3.3 

What environment (browser version, Tomcat version, JVM version, server OS)?
Chrome, IE; apache-tomcat-8.0.0-RC10, Windows

Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)
org.springframework.web.util.NestedServletException: Request processing failed; 
nested exception is java.lang.RuntimeException: No container found for your 
server: Apache Tomcat/8.0.0-RC10
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:583)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:59)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:729)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:467)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:392)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:319)
	at org.apache.jasper.runtime.PageContextImpl.doForward(PageContextImpl.java:734)
	at org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:704)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:63)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:403)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:347)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:221)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:107)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:616)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:155)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:76)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:934)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:90)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1015)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:646)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1576)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1534)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.RuntimeException: No container found for your server: 
Apache Tomcat/8.0.0-RC10
	at com.googlecode.psiprobe.controllers.apps.ListWebappsController.handleRequestInternal(ListWebappsController.java:43)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:54)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	... 49 more
Caused by: java.lang.NullPointerException
	at com.googlecode.psiprobe.controllers.apps.ListWebappsController.handleRequestInternal(ListWebappsController.java:41)
	... 55 more

```

Original issue reported on code.google.com by `robertya...@gmail.com` on 8 Jan 2014 at 8:31

### PR DESCRIPTION
**Pull request by henry-caballero**
** This fix raises Java compatibility to 1.5 for invoking a new API method by reflection **

### CODE REVIEW

**Comment by henry-caballero** [comment]
** Details **

Managed to solve it by looking at Tomcat sources and now probe lists both global and application resources in Tomcat 8.0.21.

The problem lies in the ```ResourceResolverBean``` not being able to bind to naming contexts, basically because the security check changed and silently fails. Before Tomcat 8.0.6 a ```null``` token worked for binding (the verification was kind of messed) but now the ```NamingContextListener``` and ```StandardContext``` use a new attribute ```namingToken```, so a ```null``` token no longer works. ```ResourceResolverBean``` then operates on probe's own JNDI context and won't look up any resource.

Given the attribute doesn't exist in previous versions I'm getting it through reflection to preserve Tomcat 5.5.23+ compatibility but this forced me to raise JVM to 1.5. Anyway the fix will work for those with newer environments (JVM 1.5+). For global resources, the global JNDI context is now retrieved from the server's ```getGlobalNamingContext()``` method, this way ```java:``` prefix must be omitted.

Here's an overview of the fix:

```
	/**
	 * Returns the security token required to bind to a naming context.
	 *
	 * @param context the catalina context
	 * 
	 * @return the security token for use with <code>ContextBindings</code>
	 */
	protected Object getNamingToken(Context context) {
		
		//null token worked before 8.0.6
		Object token = null;
		if (!ContextAccessController.checkSecurityToken(context, token)) {
			try {
				//namingToken added to Context and Server interfaces in 8.0.6
				//Used by NamingContextListener when settinp up JNDI context
				java.lang.reflect.Method mGetNamingToken = context.getClass().getDeclaredMethod("getNamingToken");
				token = mGetNamingToken.invoke(context);
				
				if (!ContextAccessController.checkSecurityToken(context, token)) {
					logger.error("Couldn't get a valid security token. ClassLoader binding will fail.");
				}
			}
			catch (Exception e) {
				logger.error("There was an error getting namingToken through reflection", e);
			}
		}
		
		return token;
	}
	
    public synchronized List getApplicationResources(Context context, ContainerWrapperBean containerWrapper) throws NamingException {

        List resourceList = new ArrayList();

        boolean contextAvailable = containerWrapper.getTomcatContainer().getAvailable(context);
        if (contextAvailable) {

            logger.info("Reading CONTEXT " + context.getName());

            boolean contextBound = false;
			Object token = getNamingToken(context);
			
            try {
                ContextBindings.bindClassLoader(context, token, Thread.currentThread().getContextClassLoader());
                contextBound = true;
            } catch (NamingException e) {
                logger.error("Cannot bind to context. useNaming=false ?");
                logger.debug("  Stack trace:", e);
            }
	...

	/**
	 * Returns the Server's global naming context
	 *
	 * @return the global JNDI context
	 */
	protected javax.naming.Context getGlobalNamingContext() {
		
		javax.naming.Context globalContext = null;
		MBeanServer mBeanServer = getMBeanServer();
		if (mBeanServer != null) {
			try {
				ObjectName name = new ObjectName("Catalina:type=Server");
				Server server = (Server) mBeanServer.getAttribute(name, "managedResource");
				//getGlobalNamingContext() was added to Server interface in Tomcat 7.0.11
				if (server instanceof StandardServer) {
					globalContext = ((StandardServer) server).getGlobalNamingContext();
				}
			} catch (Exception e) {
				logger.error("There was an error getting globalContext through JMX server:", e);
			}
		}
		
		return globalContext;
	}
	
	public void lookupResource(ApplicationResource resource, boolean contextBound, boolean global) {
	DataSourceInfo dataSourceInfo = null;
	if (contextBound) {
		try {
			javax.naming.Context ctx = !global ? new InitialContext() : getGlobalNamingContext();
			String jndiName = resolveJndiName(resource.getName(), global);
			Object o = ctx.lookup(jndiName);
	...
```

Tested on RHEL 7, Server JRE 1.8.0_40, Tomcat 8.0.21 and Probe 2.4.0-SNAPSHOT.

This is my first contribution, please let me know how it looks and how to attach the whole file.

**Comment by jander99** [comment]
Probe 2.x relies on Java 1.4+, not Java 1.5.  

Unfortunately if Java 1.5 is required for Tomcat 8 functionality, I would say this ends the life of Probe 2.x, but would need @MALfunction84 buyin on that.

**Comment by henry-caballero** [comment]
Java 1.5 is only needed to bind the ClassLoader to the naming context using a valid security token, and so far the way I found to get the token relies in reflection, but any other way to circumvent the token requirement would do, preserving Java 1.4 compatibility.

You can look into apache's ```ContextBindings``` and ```ContextAccessController``` to figure out a way, I tried writing and accessor class in the org.apache.naming package to get the naming context without actually binding with no luck (```IllegalAccessError```).

**Comment by MALfunction84** [comment]
If we can find a way to push resource resolution down into the TomcatAdaptor [sic], it could use Tomcat APIs directly. Could that avoid the reflection and the Java version bump?

**Comment by henry-caballero** [comment]
That makes perfect sense, maybe not the entire resource resolution but just the context binding.

I'm commiting changes to 9 files pushing the context binding down to the ```AbtractTomcatContainer```. Tomcat 8.0 adaptor overrides the default behaviour by using the API's directly as you suggested.

Tested on RHEL 7, Server JRE 1.8.0_40, Tomcat 8.0.21 and Probe 2.4.0-SNAPSHOT. Working fine with Java 1.4.

Ps. I'm commiting by web given I can't right now from command line, but I'm halfway and won't let me commit any more file (I guessing cause the travis build failed). Any hint?

**Comment by henry-caballero** [comment]
https://github.com/MALfunction84: Everything is sorted out in pull request https://github.com/psi-probe/psi-probe/pull/467

**Pull request closed without merging**
