### PR TITLE
Update travis to use docker builds, automate snapshot release, jacoco only

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by hazendaz** [comment]
This is not testable until it actually hits master.  Preliminary test was just to ensure communication to sonatype and coveralls.  If anything shakes out on this it will be addressed after being applied to master.  

*** At the moment, coveralls is disabled from how it ran before.  Fixing that now before merge...

**Comment by jander99** [comment]
Since I know you're actively working on it, lets (hopefully not) break the build to add the new docker changes.

**Comment by jander99** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project psi-probe: Failed to deploy artifacts: Could not transfer artifact com.github.psi-probe:psi-probe:pom:3.0.0-20160313.201945-2 from/to ossrh (https://oss.sonatype.org/content/repositories/snapshots): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/com/github/psi-probe/psi-probe/3.0.0-SNAPSHOT/psi-probe-3.0.0-20160313.201945-2.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]

**Comment by hazendaz** [comment]
@jander99 Hang tight on this as another pull is coming.  I'm still in the middle of this.  It requires me to have it in pull request area so I can fix coverage tools.  I'll deal with security issues shortly.

docker build doesn't have any impact on anything unless sudo is used which isn't for this project.  I just happened to catch it was still on legacy travis ci builds.

**Comment by jander99** [comment]
@hazendaz no worries, I'm good with working through this.  I know you won't leave something in a bad state.

**Comment by hazendaz** [comment]
@jander99 Security issue resolved.  Autobuilds now working.  Yet to be determined if old security check for pull requests is working as expected.  I think that kept using the master version I pushed earlier so will be testing again shortly with another pull for unrelated items.

**Pull request merged**
