### PR TITLE
Fix classloader Leak during JFreeChart initialization

### LINKED ISSUE #443: Classloader Leak during JFreeChart initialization
```
What steps will reproduce the problem?
1. Deploy probe.war
2. Access System - Memory Utilization (which starts JFreeChart)
3. Undeploy probe.war

What is the expected result?
A heap dump should not show probe classloader on the PermGen.


What happens instead?
The classloader of probe shows, which is stopped, does not get collected. See 
probeAppContextClassloaderLeak-01.png.


What version of Probe are you using?
2.3.3 and 2.4.0-SNAPSHOT

What environment (browser version, Tomcat version, JVM version, server OS)?
Chrome 40 64 bits, Tomcat 7.0.57, Java 1.7.0_60 64 bits (Oracle), Windows 7 64 
bits 

Please provide any additional information below.

The root cause can be viewed on probeAppContextClassloaderLeak-02.png

Add a patch solution as described at 
https://plumbr.eu/blog/hunting-down-memory-leaks-a-case-study

```

Original issue reported on code.google.com by `diogosan...@gmail.com` on 27 Jan 2015 at 5:37

Attachments:
* [probeAppContextClassloaderLeak-01.png](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/probeAppContextClassloaderLeak-01.png)
* [probeAppContextClassloaderLeak-02.png](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/probeAppContextClassloaderLeak-02.png)
* [psi-probe-patch.txt](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/psi-probe-patch.txt)

### PR DESCRIPTION
**Pull request by diogosantana**
Fixed #443.

### CODE REVIEW

**Comment by hazendaz** [comment]
I realize this was pulled in but wondered if any thought had been given to including this listener?  It effectively does the same and more.

https://github.com/mjiderhamn/classloader-leak-prevention

**Comment by diogosantana** [comment]
Seams to be a good framework. When I proposed the patch, I didn't hit this
framework on my research. It would save me a lot of time.



Diogo Sant'Ana

**Comment by hazendaz** [comment]
I've been running this framework for a couple of years.  Works great for most setups.  It doesn't work in all cases and it mentions that but probably is safe here.  If it was to be used would need some extended testing unloading and reloading psi probe to make sure no stack traces.  It does a lot and at the moment not configurable enough in case not everything is needed.  I've seen it fail with mule esb but has worked with everything else I've tried it with.

--- Original Message ---

**Comment by diogosantana** [comment]
Could you create a issue to consider the use of it?

**Comment by hazendaz** [comment]
Sure.  It sounds like a great thing to try given what this library is for.  I'll create an issue later this weekend.

--- Original Message ---

**Pull request merged**
