### PR TITLE
[leaks] Add try with resources to ensure resources are closed (found per sonarqube)

### PR DESCRIPTION
**Pull request by hazendaz**
@MALfunction84 Need a review on this as I'm a bit unsure what actions outside of the keystore/truststore piece needs to be tested.  I was aware of the keystore/truststore leak as I experienced inability to delete a keystore after reading it but the other is more broad so not sure what I should check before assuming that is ok.

### CODE REVIEW

**Comment by MALfunction84** [comment]
I'm afraid I won't be much help here.

**Comment by diogosantana** [comment]
I will test it.

**Comment by diogosantana** [comment]
Checked. The change worked.

image

**Comment by hazendaz** [comment]
Sweet!  Thanks

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Aug 1, 2016 at 11:43 PM -0400, "diogosantana" <notifications@github.com<mailto:notifications@github.com>> wrote:


Checked. The change worked.

[image]<https://cloud.githubusercontent.com/assets/5445929/17316403/ff146296-5849-11e6-817b-8aca1e12d13f.png>

-

**Pull request merged**
