### PR TITLE
Fixed #466 Missing gif

### LINKED ISSUE #466: Missing gif
Sometimes the app unsuccessfuly tries to load the gif **rb_0+6.gif** at [webapp/css/classic/gifs](https://github.com/psi-probe/psi-probe/tree/master/web/src/main/webapp/css/classic/gifs)

Chrome error:
http://localhost:8080/probe/css/classic/gifs/rb_0+6.gif Failed to load resource: the server responded with a status of 404 (Not Found)

image

### PR DESCRIPTION
**Pull request by diogosantana**
Fixed #466 Missing gif

### CODE REVIEW

**Comment by diogosantana** [comment]
I will close this PR to rebuild it and try to find out why git identified so many changes on unchanged lines.

Any tips to avoid that?

**Comment by diogosantana** [comment]
I just realize it was correct. I pull out a lot of lines from `VisualScoreTag.doAfterBody()` to `VisualScoreTag.calculateSuffix`.

Sorry about the mess.

**Comment by MALfunction84** [comment]
Abstracting out the calculation is good. The reason it's reporting so many differences is because your code formatting is off. You're using tabs in place of 8 spaces. Can you fix this before I merge?

**Comment by diogosantana** [comment]
Yeah. Give me some hours.


Diogo Sant'Ana

**Pull request closed without merging**
