### PR TITLE
[cert] Certificates tab works again in Tomcat 7/8. Fixes #1000

### LINKED ISSUE #1000: Tomcat 7/8 no longer show cert information
Patches to support org/apache/tomcat/util/net/SSLHostConfig cause failure with tomcat 7/8.  We need to allow for backwards compatibility.

### PR DESCRIPTION
**Pull request by diogosantana**
Fixes #1000.

I don't know why Eclipse changed import orders...

### CODE REVIEW

**Comment by hazendaz** [comment]
alt-shift-o to import will cause eclipse to re-order things.

**Comment by hazendaz** [comment]
@diogosantana This does not fix the issue.  Did you test this solution?  I'm using tomcat 8.0.39, and it gets an exception internally and doesn't set the keycerts.  My thought to fixing was to just populate the new objects you created with the legacy information.  At the moment, I still get a blank result.

**Comment by hazendaz** [comment]
specifically -> keyStoreCerts of certificateInfos is null.  Therefore it won't be able to be displayed on the webpage as it expects the new layout.  I'm not sure an extension to connectorInfo makes sense here considering internal certificate info is still setup and that is what the page wants.  We are just faking tomcat out here in this case so we need to mirror into into it as if the object really exists.

**Comment by hazendaz** [comment]
I got it...needed null checks from original code and could use the same object not changing object type which isn't otherwise used later on.  PR coming shortly.

**Comment by diogosantana** [comment]
Ok, thanks.

I know about organize import shortcut, but eclipse change to that order... I don't know if Neon changed the default order or what... anyway, it really doesn't matter.

**Pull request merged**
