### PR TITLE
Add jdeps plugin to reporting section. 

### LINKED ISSUE #457: Using JDK 8 jdeps in Maven
Just a placeholder for eventually using jdeps as a way to determine which libraries are really needed, thus cleaning up the pom file(s) for this project.  

https://github.com/marschall/jdeps-maven-plugin

The only requirement is that the build use jdk 8, not that the project is only jdk 8 compatible.  It it stands now, travis will build the project using jdk8 javac.

### PR DESCRIPTION
**Pull request by jander99**
Closes #457 .

### CODE REVIEW

**Comment by hazendaz** [comment]
Maven supports this now.  Is there any reason to not use mavens version?

<dependency>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jdeps-plugin</artifactId>
    <version>3.0.0</version>
</dependency>

**Comment by jander99** [comment]
I guess I didn't see that maven had an official build.  I'll fix that.

**Comment by hazendaz** [comment]
Maven has a nabble site.  Might be useful to follow that.  I had seen them talking about this quite a bit.  They jumped right to version 3.0.0 as first cut.  I assume this came out of the earlier beta versions before hitting there stuff.  I thend to follow what's going on in their area.  These days they are very active.

Maven nabble
http://maven.40175.n5.nabble.com/

Mojo nabble
http://mojo.10943.n7.nabble.com/Developer-f3.html

While not related in this case, I've seen maven doing some interesting things lately.  They moved sonar plugin from mojo over to sonar and finally got rid of a confusing sonar plugin that sonar kept putting up for legacy support.  I suspect a lot more of this type of thing might happen in order to help maven team keep up.

**Comment by hazendaz** [comment]
@jander99 Can you squash your commits?

**Comment by jander99** [comment]
Still learning to git. Let me know if that looks correct.

**Comment by hazendaz** [comment]
Still too many commits.  Still learning git...understandable.  Here is easiest way to get this straight.

On your forked branch

git pull --rebase upstream master

That will get it to clear everything but your commit which then will be at top.

Then to force that back out...

git push origin +master

Assumption is your are using master as I didn't look.  The plus operation states to force the push.  That will cause travis to start the build over.  We shold then see just the one commit with the change and as soon as everything passes, it can be merged.

**Comment by jander99** [comment]
Let me just rebase everything and start over. The change is quite small anyway.

**Comment by hazendaz** [comment]
Per my prior comment, this is the flow I use on my forks all the time.  It ensures we get a clean commit line coming it so the master looks good.  Basic idea is that off the master we really don't care too much about the branches it's coming from.  So basically you can do whatever you want on your specific fork and that's ok.  There are a few other ways around this as I see you just marked starting over. Sometimes that is just as easy, especailly if merge conflicts flare up.  No one ever wants to deal much with those.  Especially if the overall change is a 5 minute change vs an hour of fighting with GIT.  :)

**Pull request closed without merging**
