### PR TITLE
html updates for html5

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by jander99** [comment]
Can you move these to CSS?  Looks like 90% of the changeset is the same bit of style code.

**Comment by hazendaz** [comment]
@jander99 I'll look at doing that.  Thanks.

**Comment by hazendaz** [comment]
Closing for time beint to address other more pressing issues.

**Comment by hazendaz** [comment]
I'm going to reopen this and go ahead and merge it as-is.  I'll open a separate ticket to use more css throughout.  I've got a need to revert all the slf4j/logback back to versions that do not break api compatability on logging as well as update some vulnerabilties and get essentially milestone 4 released ASAP.

**Pull request closed without merging**
