### PR TITLE
Add SIFT logback.xml for support of testing our SIFT logback logic

### PR DESCRIPTION
**Pull request by hazendaz**
Please note that as noted in readme this is for manual usage to verify our SIFT appender logic with logback so we don't need to look elsewhere.  As I didn't see a real good place to put this, I just added it to the resources package on test side for web module.  If there might be a more appropriate location to store this, please advice and I'll move it.

### CODE REVIEW

**Comment by MALfunction84** [comment]
I'm not sure I understand the purpose of this. Did you mean to include some tests with it?

**Comment by hazendaz** [comment]
When I made the SIFT fix, I modified our actual logback.xml file then used that to build psi-probe to test out the solution.  It doesn't make sense for us to have that in our main logging but I didn't want to lose what I found when we need to verify SIFT appender logic.  This works by overlaying ours so that SIFT shows up without errors on the log tab.  Just wasn't sure exactly where we might keep something like this.  It's out of scope in our unit tests I think.  It's more for manual usage without having to search online to figure out SIFT appender setup.

**Comment by hazendaz** [comment]
I think I have a better idea on this.  Go ahead and decline the PR.  I'll start working on building out a new series of psi-probe - demos instead which will cover all our various log support for starters including this one.  That way we will have a better way to test our internal support.  Basically each demo will be simple servlet using different logging setups.  Sound like a better approach?


Sent from Outlook Mobile






On Tue, Feb 2, 2016 at 9:34 PM -0800, "Mark Lewis" <notifications@github.com> wrote:





I'm not sure I understand the purpose of this. Did you mean to include some tests with it?

---

**Comment by hazendaz** [comment]
Closing this pull request.  Will create some demo applications that include such things instead.

**Pull request closed without merging**
