### PR TITLE
Maven reporting

### PR DESCRIPTION
**Pull request by jander99**
Updated Reporting capabilities by adding JXR, Checkstyle, PMD, and L10n Status.  This commit will provide a report in via the site command of similar code issues that should be remediated as those found using an IDE.  
Also, commented out the dependency-check plugin, as it was noisy and slowed down builds. This can be reenabled or the pom can be changed to have this run on builds only.

### CODE REVIEW

**Comment by MALfunction84** [comment]
Can you correct the indentation? Tabs in pom.xml.

**Comment by hazendaz** [comment]
Ultimately, I think you will come around to seeing why tabs are bad and going to spaces.  However, that is a do all at once agains the library.  Spacing is more consistant across workspaces, tabs can always vary.  However, easier said than done setting up eclipse correctly, but it can be done.  I'm on the spacing camp and have been for a few years.  I've got another project I work on that auto formats the project.  If and when ready, let me know and I'll add it here.  Then I'll have it to you to do a one time pass to format everything.  That way you can be certain the changes are for the better of the library without causing issues.

**Comment by hazendaz** [comment]
For now, I agree, keep it as is.

**Comment by jander99** [comment]
Fixed spaces.

**Comment by MALfunction84** [comment]
Hmm, not sure what happened but it can't automatically merge. Rebase?

**Comment by jander99** [comment]
I think because others were also messing with the same sections of pom.xml.  I might need to start over with it. Let me check once I'm home.

**Comment by MALfunction84** [comment]
@jander99 Looks like it was 47cf7eb.

**Comment by jander99** [comment]
I think IntelliJ can rebase with a few clicks, so I'll do that to this branch and hopefully that cleans things up.

**Comment by hazendaz** [comment]
Sorry about that...

--- Original Message ---

**Comment by MALfunction84** [comment]
@hazendaz You just beat him to the punch adding ```<properties>```. :)

**Comment by jander99** [comment]
I got frustrated trying to get git/github/intellij to rebase properly.  So I copied out my pom.xml and deleted everything. I'll start over with a fresh PR in a few minutes.

**Comment by hazendaz** [comment]
Sometimes that is the easiest.  Sounds like you are having one of those famous git moments where you just curse at the tool. @$!#

--- Original Message ---

**Comment by MALfunction84** [comment]
Now seems like a good time to change all the indentation. :stuck_out_tongue:

**Comment by jander99** [comment]
NO haha.  I'm almost done and ready to submit a PR.  As far as indentation goes, We can discuss the rules we want in the forums, and someone can set up IntelliJ/Netbeans/Eclipse or whatever to obey that style. I know Eclipse and IntelliJ can reformat code based on those rules for the entire project.  Just let that be a commit on its own.

**Comment by hazendaz** [comment]
i second formatting.  There is a plugin I'ved used and worked on to extensively to get to eclipse 4.4.1 support.  It's going through some organizational changes but likely is to see release soon under new ownership.  Once available, I can work it into this project.  The initial run though, I'd prefer @MALfunction84 to activate it for the first run.  Only because it is somewhat intrusive that first run.  That also sort of means any pull requests at the time will certainly be useless or need work so it just needs done when no PRs.  After the first go, it can remain activated.  At the moment, it only applies to java code and biggest change is to use spaces rather than tabs.  Obviously configurable but spaces I believe is preferrable.  We expect to eventually get xml formatting in that library as soon as dust settles and we can reach out to another forker from long ago that did that but under much greater changes from the original.  Hopefully we can merge those together.  Plugin name currently was going by maven-java-formatter-plugin and has been rebranded this week as formatter-maven-plugin.

**Comment by MALfunction84** [comment]
I was half-joking about reformatting. It's going to be very disruptive, so the time to do it is probably right before creating the 2.4 branch.

As for tabs vs spaces, let's not get into that here. Open a thread on the Google Group or something and we'll all wax philosophical there. :)

**Comment by jander99** [comment]
I have a branch with formatting changes via IntelliJ.  I wanted to see what you thought of #509 first. 

@hazendaz I could do the same in Eclipse.  I use both regularly.

**Comment by MALfunction84** [comment]
I've filed #512 for reformatting. I agree that it's needed. Also created [a thread on the Google Group](https://groups.google.com/forum/#!topic/psi-probe-discuss/z6GtjJni_iE) to try to keep the debate separate from the work. Feel free to present your cases for spaces. :)

**Pull request closed without merging**
