### PR TITLE
Created new tab Certificates

### PR DESCRIPTION
**Pull request by diogosantana**
Created new tab Certificates as a most complete solution to #659.

The tab will show the following list of certificates:

- System key store certificates
- System trust store certificates
- Connectors key store certificates
- Connectors trust store certificates

@hazendaz please let me know if it still is with line ending problem

### CODE REVIEW

**Comment by hazendaz** [comment]
@diogosantana Line endings problems have been resolved.  Thanks.

As for this change, what should I be expecting to occur?  I've got certificates setup for tomcat only on the connectors.  In my specific use-case on my local machine I just have a keystore.  When I pull this PR and run a quick test, it's essentially other than showing the following words...

Connectors Certificates
http-nio-8443

What I don't have setup are JVM arguments and I sort of feel those are a problem in general as it allows the password to easily be determined.  My assumption was that this PR might show me results similar to that if I had the JVM properties defined.  Is that not yet the case?

**Comment by diogosantana** [comment]
Hum... I test it all and work on a Tomcat 8.0.32 (the zipped one).
Any log errors?

**Comment by diogosantana** [comment]
This is my example with two connectors.
probe-certificates

**Comment by hazendaz** [comment]
System Certificates on the certificate tab work just fine.  Connectors one is not working.  It might be at least helpful to review the code a little more to post some sort of message like "not configured" in case there are none.  It's possible my configuration is not 100% correct.  Until last week, I thought it was ok to have both keystore and truststore in same file.  I know a bit more now.  So potentially I have something else setup wrong.  I'm otherwise ok with the changes.

@jander99 
@MALfunction84 

Can either of you give this a test and see if you are able to accurately see the connector certificates?  I'm very eager for this to work :)  Ultimately if this works, I think next is ability to add/delete/update/etc is quite possible and saves a huge amount of work for a system admin that doesn't do this often :)

**Comment by hazendaz** [comment]
@diogosantana 

Now that you are bringing jmockit into the project (+1)...maybe you can work out some more tests to raise general coverage in other areas.  I'm all for jmockit even though I personally feel the owner of jmockit needs a more consistent api from version to version but at least 1.21 and few versions before are extremely stable for anyone with past experience with jmockit library.  It used to be a really rocky ride from version to version.  I've been using it for a couple of years now over roughly 100K lines of code so I know it's power and it's power is awesome outside of my complaints!

**Comment by diogosantana** [comment]
@hazendaz Can you show your connector config? By the way, this should only show JSSE. It won't show connectors that are not marker as SECURE or that uses APR/Native or AJP.

**Comment by hazendaz** [comment]
Here is the general setup I use...

<Connector SSLEnabled="true" clientAuth="false" keystoreFile="someKeystoreFile.jks" keystorePass="xxxxxxxx" port="8443" scheme="https" secure="true" sslProtocol="TLS"/>

Does that look correct?

**Comment by diogosantana** [comment]
@hazendaz About jmockit, I added it because I was needing mock framework to test properly and as a result of "discussion" on #596. But I'm used to use Mockito, so expect some wrongness...

My view is we don't need to spend time creating test for things we are not touching. As we create more stuff or change others, then we create tests for those.

**Comment by hazendaz** [comment]
On jmockit...no worries.  I was hoping you were very familiar with it to spread it through the code base quickly.  It will get there eventually :)

**Comment by diogosantana** [comment]
The config seams to be ok. Try to add ` protocol="org.apache.coyote.http11.Http11NioProtocol"`.
No errors on log? Can you debug it?

**Comment by hazendaz** [comment]
I have that setting too although that is default in tomcat 8 (BIO was deprecated).  I have a number of other settings too that I felt were unrelated.  I'll try debugging it.

**Comment by hazendaz** [comment]
I found the issue.  Current code doesn't support catalina.base or catalina.home starting path of keystore/truststore as allowed by tomcat.  I adjusted the code a bit on my local copy to use catalina.home.  That worked as I expected.  I assume there is a better tomcat way to read the file location and/or it's going to need to look as you have it plus catalina.base or catalina.home.

In toConnectorInfo...

if file doesn't exist, I added this to test my use-case which I think is pretty normal....

```java
 else {
        file = new File(System.getProperty("catalina.home") + File.separator + keystoreFile);
        if (file.exists()) {
          info.setKeyStoreFile(file);
        }
      }
```

**Comment by diogosantana** [comment]
It makes sense. I will look at tomcat source to be 100% sure.

Btw, I always put the full path to avoid problem... thats why it work fine
for me.
Em 16/02/2016 02:16, "Jeremy Landis" <notifications@github.com> escreveu:

**Comment by diogosantana** [comment]
There is no "System Certificates" as I put it on the view. Configuration is always per connector.

Also Tomcat never looks at `javax.net.ssl.keyStore`, but it looks at `javax.net.ssl.trustStore` if no `truststoreFile` is provided by connector configuration. So I will reproduce the same behavior to list certificates per secure connector configured.

**Comment by diogosantana** [comment]
@hazendaz 

Btw, Tomcat source code only looks at catalina.base, not catalina.home as you say it worked in your environment. Can you confirm that?

**Comment by hazendaz** [comment]
I have both set as the same location..ie default tomcat setup.  So if that is what tomcat docs state I would agree.


Sent from Outlook Mobile






On Wed, Feb 17, 2016 at 5:43 PM -0800, "diogosantana" <notifications@github.com> wrote:





@hazendaz

Btw, Tomcat source code only looks at catalina.base, not catalina.home as you say it worked in your environment. Can you confirm that?

---

**Comment by hazendaz** [comment]
@diogosantana I'm going pull this in on separate PR.  I have squashed the code leaving only the jar introductions separate.  I also found a bug in cert handling as it did not handle null pointers when cert information is not available on connector.  I did remove the one closeable that was added since it was later not used as a result of java 7.  And finally one minor log cleanup.

This is working for me now.  Thank you so much for all your hard work!  This is really great!

**Comment by hazendaz** [comment]
Closed via #678

**Pull request closed without merging**
