### PR TITLE
Removed com.googlecode from naming with pom adjustments for github - Fixes #513

### LINKED ISSUE #513: Remove com.googlecode from package names
The current package name is ```com.googlecode.psiprobe```. We should probably change it to something divorced from wherever the code is being hosted at the time. I'm thinking of going with just ```psiprobe``` since there's not really any URL out there that represents the brand or company. Any better suggestions?

### PR DESCRIPTION
**Pull request by hazendaz**
All references to 'com.googlecode' have been removed.

Poms have been adjusted per converstation on #513 

GroupId is now ```com.github.psi-probe```.  This is required to release to maven central or we have to purchase a domain.  Initial project request to setup has also been submitted.  If you need release access, please comment on same ticket.

Sonatype ticket [here](https://issues.sonatype.org/browse/OSSRH-20153)

ArtifactId's are

```xml
psi-probe
psi-probe-core
psi-probe-tomcat7
psi-probe-tomcat8
psi-probe-tomcat9
psi-probe-web
```

psi-probe-web is still setup to have final name of 'probe.war'

All configuration files have had same change made.

```<name>``` tag in poms should match artifactId per maven convention so that was changed.  Previously, it used that in combintation with ```<description>``` to describe the project.  I moved the old ```<name>``` and applied that to ```<description>``` so context is not lost.  This is more important with myeclipse users and deployments to sonar where names otherwise change from expected.

The project folders technically should be renamed now too.  However, they have not been.  I left a comment in the parent pom on the modules noting that should be done in a phase two.  This way it doesn't impact modules already imported into IDE.  Otherwise we would have to re-import so this approach is most cost effective for time being so it preserves IDE history as well*.  We can revisit renaming that closer to end of 3.0.0 cycle.

* History for local changes is intact.  Trying to use git commit history in eclipse is a  no-go.

### CODE REVIEW

**Comment by MALfunction84** [comment]
:thumbsup:

**Comment by hazendaz** [comment]
mark down deleted some of my comments on last paragraph so updating that now so it doesn't sound like something is missing :)

**Comment by hazendaz** [comment]
I will hold off merging this until #617 is addressed.

**Comment by hazendaz** [comment]
Rebased this but holding until other minor patches come in first.

Additionally fixed groupId to be ```com.github.psi-probe``` per sonatype request on jira ticket.

**Comment by jander99** [comment]
@hazendaz Please check this again now that #617 is closed.  GH reporting merge conflicts.

**Comment by hazendaz** [comment]
I'll rebase this tonight.  Thanks


Sent from Outlook Mobile






On Tue, Jan 26, 2016 at 6:22 AM -0800, "Jeff Anderson" <notifications@github.com> wrote:





@hazendaz Please check this again now that #617 is closed.  GH reporting merge conflicts.

---

**Comment by hazendaz** [comment]
This has been looked at a couple of times now so going to merge it.  I was initially concerned about merge conflicts due to other changes but so far rebases have not shown a large uptick on merge conflicts so calling this done.

**Pull request merged**
