### PR TITLE
Issue #659 Show TrustStore certificates ordered by Expiration Date. 

### PR DESCRIPTION
**Pull request by sandrapascual**
Tab: System, Down to: Wrapper Control 
Added slf4j to log the exception

### CODE REVIEW

**Comment by sandrapascual** [comment]
Hello,
I've created this new pull request to solve my problem with Git , sorry...
I've closed the previous pull request.

**Comment by hazendaz** [comment]
Perfect!  Thanks.  Someone on the team will get to this today.  Do you happen to know how to get this information from connectors?  Also would it be fairly easy to add ability to remove expired certificates or even add new ones?  All can be separate pull requests.  This is good enough for now.  I see a lot of power here and potential for making things easier.


Sent from Outlook Mobile






On Wed, Feb 10, 2016 at 12:00 AM -0800, "sandrapascual" <notifications@github.com> wrote:





Hello,
I've created this new pull request to solve my problem with Git , sorry...
I've closed the previous pull request.

---

**Comment by sandrapascual** [comment]
Hi, I've not had enougth time to investigate about it. But all of this new issues are in my taks list.
Thanks for you help!

**Comment by hazendaz** [comment]
Just as an aside we had added new security restrictions to psi probe via github settings.  It appears that forces everyone to be sync'd.  Tonight I will be adjusting the setting or otherwise taking care of current pull request.  Sorry for the delay.


Sent from Outlook Mobile






On Thu, Feb 11, 2016 at 2:00 AM -0800, "sandrapascual" <notifications@github.com> wrote:





Hi, I've not had enougth time to investigate about it. But all of this new issues are in my taks list.
Thanks for you help!

---

**Comment by diogosantana** [comment]
This should be on Wrapper Control?

**Comment by sandrapascual** [comment]
I think it is better to maintain this separate. But it is only my opinion...

**Comment by hazendaz** [comment]
Sorry didn't get to this last night.  I will this weekend.


Sent from Outlook Mobile






On Fri, Feb 12, 2016 at 12:04 AM -0800, "sandrapascual" <notifications@github.com> wrote:





I think it is better to maintain this separate. But it is only my opinion...

---

**Comment by hazendaz** [comment]
Merged via #666

**Pull request closed without merging**
