### PR TITLE
Fixes #573 Error stopping/starting an app with Probe 2.4 under Tomcat 8

### LINKED ISSUE #573: Issue when stopping/starting an application with Probe 2.4 under Tomcat 8
With tomcat 8 (8.0.24, but I doubt it comes from the subversion ?), and Probe 2.4 official release, you can't stop/start an application by clicking on the green or red status in the application list.

It generates an error on logs
ERROR com.googlecode.psiprobe.controllers.apps.AjaxToggleContextController  - java.lang.NoSuchMethodError: org.apache.catalina.Context.getAvailable()Z

You can still stop/start it by clicking on the application and then using the stop/start button on top though as a workaround, but it was nice to be able to do it from the main screen.

It works fine with Tomcat 7 FYI.

### PR DESCRIPTION
**Pull request by diogosantana**
Fixes #573 Error stopping/starting an app with Probe 2.4 under Tomcat 8.

org.apache.catalina.Context.getAvailable() were deprecated in Tomcat 7
and a note were added stating it will be removed in Tomcat 8. Therefore,
the java.lang.NoSuchMethodError at
org.apache.catalina.Context.getAvailable().

### CODE REVIEW

**Comment by diogosantana** [comment]
It depends on #626, but I can change that if needed.

**Comment by hazendaz** [comment]
As suspected this one will need to wait until after logs addressed or if you close this PR, branch off master, and make just the location deprecation fix.


Sent from Outlook Mobile






On Mon, Jan 25, 2016 at 8:58 PM -0800, "diogosantana" <notifications@github.com> wrote:





It depends on #626, but I can change that if needed.

---

**Comment by jander99** [comment]
@diogosantana Can you split these into two PRs?

**Comment by hazendaz** [comment]
@diogosantana Probably best thing to do here as it will be quicker is to close this pull request, create a new branch off master with only the tomcat 8+ fix, then submit a new pull request for the same.  I'll immediate merge that.

btw Good catch!

**Comment by diogosantana** [comment]
Jeremy, I can do that but i'm unable now. Next week for sure.


Diogo Sant'Ana

**Pull request closed without merging**
