### PR TITLE
Fix issue #505 correct locations of resources

### PR DESCRIPTION
**Pull request by hazendaz**
Same results except that context.xml is not duplicated under WEB-INF.  Being
that it was reported the correct location was under META-INF for jboss only and having
used context xml in that location back to tomcat 6, I believe this is
ok.  I do not know going back to tomcat 5 or 5.5 if that was true but certainly is for 6+.

btw - lines are not normalized so this style of move caused normalization changes.  I did only move the files.  There are no changes except pom.xml.  We should add .gitattributes so we normalize the code base.  It might even be advisable to do that before this PR is merged to be certain that I didn't change anything :)

### CODE REVIEW

**Comment by MALfunction84** [comment]
Older versions of JBoss do require context.xml under both META-INF and WEB-INF. Check out the comments in #83 starting [here](https://github.com/psi-probe/psi-probe/issues/83#issuecomment-81729675) for the history. When we drop support in 3.0, this will be safe to remove. For now, removing it is likely to cause a regression.

Changing all line endings is akin to reformatting code; it completely breaks continuity for forkers and will cause merge conflicts. I agree that it needs to be done, but let's wait until right before we cut 2.4 loose and do it all at once.

If you can fix these two things, I can merge with a clear conscience.

**Comment by hazendaz** [comment]
Do you know of a good way to change line endings?  It only showed as moves on my machine.  The changes showed after it his git.  I'll play around with normalization locally just to see how large of a problem this currently is.  I'm sure it's not isolated to just these few files.  With any luck I can get this fixed and back up including context.xml file tonight.

--- Original Message ---

**Comment by MALfunction84** [comment]
I've always used Notepad++ for changing line endings, encoding, etc.

**Comment by hazendaz** [comment]
I've tried various ways to get this working and nothing seems to work.  So let's just wait on this until either right after line normalization occurs or in 2.4.x.  I did check line normalization and it is pretty much everything.

I'm closing this for now.  I'll keep my branch and bring this back up later.

**Pull request closed without merging**
