### PR TITLE
Switch logging to slf4j facet usage only and two minor spelling issues

### PR DESCRIPTION
**Pull request by hazendaz**
This is mostly a subset of #626 but does not introduce additional unused loggers or address some output messages that are helpful.  I've asked @diogosantana to rebase once this comes in so we can get the remainder of changes being suggested.

### CODE REVIEW

**Comment by MALfunction84** [comment]
Can we also remove the Commons Logging dependencies?

**Comment by hazendaz** [comment]
It was previously removed.  What it has is jcl-over-slf4j which is tricked to act like commons-logging.  We still need that for libraries like spring that log to commons-logging so we don't lose logs.  So in that case what happens is that spring continues thinking it's logging to commons-logging which jcl-over-slf4j intercepts and then sends to slf4j and ultimately to whatever logger we are using (logback in this case).

**Comment by diogosantana** [comment]
I can't rebase without too much conflicts due to package renamed. You could apply this so I can make the others changes.

**Comment by hazendaz** [comment]
Sorry about that.  I'll merge the code tonight.  My changes do conflict some based on your logic for logging.  We can talk more about that in issues if you want to open one to discuss it further.  Do go ahead on adding loggers to prevent us from using tomcat though as that makes sense now.


Sent from Outlook Mobile






On Wed, Feb 3, 2016 at 11:54 PM -0800, "diogosantana" <notifications@github.com> wrote:





I can't rebase without too much conflicts due to package renamed. You could apply this so I can make the others changes.

---

**Pull request merged**
