### PR TITLE
Update showjsps.jsp

### PR DESCRIPTION
**Pull request by tachtler**
Hi,

last modified has a line break inside the column. Changing the width from 140 to 170 will solve this.

Thank you
Klaus.

### CODE REVIEW

**Comment by hazendaz** [comment]
Any chance you can post screen shot showing issue?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
No need for screen shot.  I ran pre and after code.  I saw the issue.  Thanks for fix.

**Comment by tachtler** [comment]
Hi Jeremy,

thank you for merge teh small change!

Klaus.

**Comment by hazendaz** [comment]
No problem.  Good catch on that.  Ive been hitting that page for weeks and didnt notice it until you pointed it out.  Keep up the good work!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request merged**
