### PR TITLE
Fix defect introduced by #527 causing maven to filter connectors.jsp …

### PR DESCRIPTION
**Pull request by hazendaz**
…resulting in use of project name

### CODE REVIEW

**Comment by MALfunction84** [comment]
Is this the same as #690?

**Comment by hazendaz** [comment]
It's the same with addition of java docs reflecting the name change.  It wouldn't merge cleanly otherwise thus second set of changes.


Sent from Outlook Mobile






On Tue, Mar 8, 2016 at 8:02 PM -0800, "Mark Lewis" <notifications@github.com> wrote:





Is this the same as #690?

---

**Comment by MALfunction84** [comment]
I don't think the javadoc on private fields is strictly necessary.

**Comment by hazendaz** [comment]
Javadocs exist everywhere per jautodoc last year.


Not sure if there is some slight confusion.  This fix was made against 2.4 and master.  Only 2.4 branch was merged.  Can you reopen and merge?


Sent from Outlook Mobile






On Wed, Mar 9, 2016 at 8:19 PM -0800, "Mark Lewis" <notifications@github.com> wrote:





I don't think the javadoc on private fields is strictly necessary.

---

**Comment by MALfunction84** [comment]
Sorry, I misunderstood.

**Comment by hazendaz** [comment]
Thanks Mark


Sent from Outlook Mobile






On Fri, Mar 11, 2016 at 9:55 PM -0800, "Mark Lewis" <notifications@github.com> wrote:





Merged #692.

---
Reply to this email directly or view it on GitHub:
https://github.com/psi-probe/psi-probe/pull/692#event-587268562

**Pull request merged**
