### PR TITLE
Optimize imports.

### PR DESCRIPTION
**Pull request by jander99**
Run IntelliJ IDEA "Optimize imports" tool.  This tool reorganizes the import statements and removes those that are no longer needed.

### CODE REVIEW

**Comment by jander99** [comment]
Yeah, this PR is huge.  It's more of a test of our resolve when there are larger changesets that come through during 3.x development.

**Comment by hazendaz** [comment]
Ummm...intelliJ import cleanup scares me.  I've washed it trash a library too many times and that is using 14.x.  Eclipse does this cleanup too and I've never seen it fail.  You seem to be heavy intellij user so maybe something I did wrong when playing around with it.  Otherwise no concerns from me.  If we are going the cleanup route might be a few things happening as we get there.  All will certainly be huge.

**Comment by MALfunction84** [comment]
This is definitely needed, because it's not at all consistent. What are our options across IDEs for how it's configured? Besides just moving imports around, I want to get the configuration committed so people who check out the project don't have to take any extra steps. (Same for code formatting, but that's another topic.)

IntelliJ seems to have weird ideas about the order imports should come in. I noticed it puts java.* and javax.* at the bottom, then everything else at the top. Doesn't Eclipse do the reverse? Or is that configurable? I know it's configurable in NetBeans, including whether it puts empty lines between the groups. By default it just puts things in alphabetical order with no empty lines.

I don't have a strong preference about the ordering of imports or how they're grouped. Please chime in. Would it be worthwhile to have the PSI Probe imports grouped?

**Comment by jander99** [comment]
I'm at work right now, so only have access to Eclipse.  IntelliJ's help gives instructions on how to export settings to a jar file:  https://www.jetbrains.com/idea/help/exporting-and-importing-settings.html
I think Eclipse exports to an xml file.  Not sure about Netbeans but probably similar.  

Sounds like someone or a group of someones will need to come up with 3 files, one for each IDE.  

There is also https://github.com/revelc/formatter-maven-plugin but it looks like it only does Java, not xml/js/css/etc.

**Comment by hazendaz** [comment]
You discovered some of my work...you are right java formatter maven plugin in only java.  There is another fork which I think we are going to reach out and try to bring together.  This formatter works independent of eclipse.  So it works across all three ide's.  I'm an eclipse guy so I like it.  I think though we really only want one formatter though.  No real preference otherwise.

--- Original Message ---

**Comment by jander99** [comment]
Well, how about that?

I did find this.  Thoughts?

https://code.google.com/p/google-styleguide/source/browse/trunk

**Comment by hazendaz** [comment]
Junit applied google format.  I'm all for it.

--- Original Message ---

**Comment by jander99** [comment]
I will see about importing this to IntelliJ and updating this PR.  I'll
post on the forum the location of the guides.  We can figure out there how
best to distribute it.

Want to keep the issue on message and the forum should be the goto play to
discuss.

**Comment by MALfunction84** [comment]
If we're indeed going with Google formatting, this PR is not the [correct ordering of imports](https://google-styleguide.googlecode.com/svn/trunk/javaguide.html#s3.3.3-import-ordering-and-spacing). ```javax``` should come after ```java```.

Also, their grouping of ```com.google``` imports at the top would be analogous to us grouping ```com.googlecode.psiprobe``` at the top. (Note to self: update package names in 3.0 to something a little more future-proof.) Thoughts?

**Comment by jander99** [comment]
Yeah keep this PR on ice for a few days. I'll get around to checking out
the features IntelliJ has to import a formatting XML document.  Hopefully
it's that easy.  Otherwise, I'll close the PR and we can keep discussing.

**Comment by MALfunction84** [comment]
Reordering imports is one thing. [Reformatting all of the source is another](https://www.youtube.com/watch?v=V_jy9atgThc&feature=youtu.be&t=146). I mentioned in #512 that we probably shouldn't apply the reformatting until just before we create the 2.4 branch. This way it doesn't create enormous conflicts for anyone who has a fork of master and is working on 2.4's final features. Any thoughts on that timing? Probably should discuss in #512.

**Comment by jander99** [comment]
You require additional pylons.

**Comment by hazendaz** [comment]
I'd say we wait until after 2.4 so it's far easier to track down any bugs found in the release.  Then do that early in the next round.  Also cut a branch of 2.4 at that time just in case regressions found later.

--- Original Message ---

**Comment by jander99** [comment]
I can agree with that sentiment.  I'll close this PR and we can revisit later.  

However, I would like to get the discussion going on whether or not we are good on 2.4.  I have it deployed to Tomcat 8 with no issues, however I am not using it to its fullest abilities as a replacement for manager/ and host-manager/.

**Comment by MALfunction84** [comment]
@hazendaz Agreed, mostly. I'm not clear on how applying the reformat after 2.4 helps us track down bugs, though.

I was suggesting we do the reformat, then create a 2.4 branch, then tag/release 2.4.0. This way, master and the 2.4 branch have the same formatting which should reduce the friction in merging fixes between the two if that becomes necessary later. We'll still have the 2.4 branch and 2.4.0 tag to be able to make sense of any stacktraces we see.

The [2.4.0 Milestone](https://github.com/psi-probe/psi-probe/milestones/2.4.0) has the remaining issues. We can probably close #394, but #490 seems to affect several versions, including Tomcat 8.

**Comment by hazendaz** [comment]
Valid points on when to do it.  At end sounds better now.

--- Original Message ---

**Comment by hazendaz** [comment]
Details on the google way…

 

http://google-styleguide.googlecode.com/svn/trunk/javaguide.html

**Pull request closed without merging**
