### PR TITLE
Fix the connector chart cannot slide to the maximum value

### PR DESCRIPTION
**Pull request by Lucien11**
Fix the connector chart cannot slide to the maximum value, and fix the bug that the slider chart cannot be changed

### CODE REVIEW

**Comment by Lucien11** [comment]
Fix the connector chart cannot slide to the maximum value, and fix the bug that the slider chart cannot be changed

**Comment by Lucien11** [comment]
Fix the bug that the connector chart cannot slide to the maximum value, and fix the bug that the chart size cannot be changed by clicking the slider

**Comment by hazendaz** [comment]
@Lucien11 Please revove the addition of mchange commons java. It's already in the project at a newer version.  It's a transient of c3p0.  Also, please remove the java.mail adjustment.  I went ahead and applied that separately as unrelated formatting.

**Comment by hazendaz** [comment]
@Lucien11 Can you also post a screen shot showing before and after?  I'm not very java script savy so a screen shot will help me understand what this is fixing.  I do realize I see IE4 being removed which is long overdue.  Thanks.

**Pull request closed without merging**
