### PR TITLE
Fix defect introduced by #527 causing maven to filter connctions.jsp …

### PR DESCRIPTION
**Pull request by hazendaz**
…resulting in use of project name

### CODE REVIEW

**Comment by hazendaz** [comment]
Fixes #687.  This issue has been long standing affecting 2.4.0 release.  It was noted on each 3.0.0 milestone and with help from @e1d this has been resolved.

**Comment by MALfunction84** [comment]
Rather than adjusting the filtering, can we change the name of the property? Or if we're going to adjust filtering, it would be more consistent/predictable to filter out entire directories rather than single files.

**Comment by hazendaz** [comment]
Long term that was the plan.  This was more of a quick fix.  I'll look at changing the name of the field tonight and will apply to both 2.4 and 3.0.  I'll also remove my other PR.


Sent from Outlook Mobile






On Mon, Mar 7, 2016 at 7:57 PM -0800, "Mark Lewis" <notifications@github.com> wrote:





Rather than adjusting the filtering, can we change the name of the property? Or if we're going to adjust filtering, it would be more consistent/predictable to filter out entire directories rather than single files.

---

**Comment by hazendaz** [comment]
@MALfunction84 The name has been changed to protocolHandler.  As you will see it was quite a bit more extensive to pull off.  It did take me a few tries to catch everything so an extra set of eyes in there would be much appreciated.

**Comment by MALfunction84** [comment]
:+1:
@hazendaz When you backport this to 2.4, please change the milestone of #687 to 2.4.1 for changelogs and such. If you have any other fix backport candidates in mind for 2.4.1, leave a note on the issue and mention me.

**Pull request merged**
