### PR TITLE
StatsCollection#deserialize catches Throwable

### PR DESCRIPTION
**Pull request by rw7**
fixes https://github.com/psi-probe/psi-probe/issues/2290

### CODE REVIEW

**Comment by hazendaz** [comment]
It would be better to catch the actual error instead of throwable.  Can you just add to catch with the proper thrown error?  Maybe even log a better-informed error with the suggested fix to resolve it to help users.

I do plan to do work on this over the weekend.  See extra try in this not needed so if you do not get to this, I can write up an alternative as noted.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Ralf Wiebicke ***@***.***>
Sent: Friday, November 18, 2022 10:37:40 AM
To: psi-probe/psi-probe ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [psi-probe/psi-probe] StatsCollection#deserialize catches Throwable (PR #2313)


fixes #2290<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsi-probe%2Fpsi-probe%2Fissues%2F2290&data=05%7C01%7C%7C937f1f485f784ba26f4f08dac97ad484%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638043826639790100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IIw1%2FLPn6tkVr6jNBuyl%2Fsy4S4fgz8hi6W2e6AHgs%2BM%3D&reserved=0>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/psi-probe/psi-probe/pull/2313<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsi-probe%2Fpsi-probe%2Fpull%2F2313&data=05%7C01%7C%7C937f1f485f784ba26f4f08dac97ad484%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638043826639790100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bQsbnVokjS90dWuPNVqVKACx%2BH85to0uKFzAejHQMfg%3D&reserved=0>

Commit Summary

  *   d3c80ff<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsi-probe%2Fpsi-probe%2Fpull%2F2313%2Fcommits%2Fd3c80ff6e413b6021943d7a17880b6643910bc8c&data=05%7C01%7C%7C937f1f485f784ba26f4f08dac97ad484%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638043826639790100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TX1070qZI29U0ar2D8uF0HJQiKQiXcdEWc%2BCgg8mpj0%3D&reserved=0> StatsCollection#deserialize catches Throwable, fixes https://github.com/psi-probe/psi-probe/issues/2290

File Changes

(1 file<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsi-probe%2Fpsi-probe%2Fpull%2F2313%2Ffiles&data=05%7C01%7C%7C937f1f485f784ba26f4f08dac97ad484%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638043826639790100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sh1GchxIwxBn4%2BBeEkiKcEkWzqbry7Q7jPZ9xhLUclM%3D&reserved=0>)

  *   M psi-probe-core/src/main/java/psiprobe/model/stats/StatsCollection.java<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsi-probe%2Fpsi-probe%2Fpull%2F2313%2Ffiles%23diff-8d48d1b201a4422a6328a761af4a8015ab0cefd0e772f3c83cdf82f28effca5e&data=05%7C01%7C%7C937f1f485f784ba26f4f08dac97ad484%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638043826639790100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vns%2F2YDkCZHVIDqZEbMJ88jf%2B38U46YkOQWlEnu41eM%3D&reserved=0> (2)

Patch Links:

  *   https://github.com/psi-probe/psi-probe/pull/2313.patch<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsi-probe%2Fpsi-probe%2Fpull%2F2313.patch&data=05%7C01%7C%7C937f1f485f784ba26f4f08dac97ad484%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638043826639790100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3nPQ2GRoiRJuB34s5akPIzS5AGMq32iNBSmoNTI7soo%3D&reserved=0>
  *   https://github.com/psi-probe/psi-probe/pull/2313.diff<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpsi-probe%2Fpsi-probe%2Fpull%2F2313.diff&data=05%7C01%7C%7C937f1f485f784ba26f4f08dac97ad484%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638043826639790100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q7IRJ7hsZXCqBp6d0h7Vn1YmkVs8w1f6lHEvc%2Btqb%2FI%3D&reserved=0>

**Comment by rw7** [comment]
The actual error is java.lang.ExceptionInInitializerError. So if you rather want to catch the actual error, that would be
`
} catch (ExceptionInInitializerError | Exception e) {
`
But ExceptionInInitializerError is still quite generic. It may have the cause described at #2290 , but it may be something completely different as well. I could be caused by another JDK version or another version of xstream.

For me it seems, that xstream is rather fragile. It relies on internal details of the JDK that may not work in newer versions. And unfortunately xstream is not able to report such problems reliably by throwing a certain exception, but ends up with an ExceptionInInitializerError. So I'd rather want to isolate probe from any problem caused by xstream as much as possible. So if some other problem pops up, probe still works and just the deserialization is lost. Therefore I chose `catch Throwable`.

And I can't think of any fix to be suggested to the users. The `--add-opens java.base/java.util=ALL-UNNAMED` is rather a workaround, allowing things that are forbidden by default for a good reason, I assume. If that workaround would just affect probe I wouldn't care. But it affects the whole JVM including my actual business application.

**Comment by hazendaz** [comment]
@rw7 looked at the original issue again, looked at the xstream page.  the solution seems far more simple.  I'm going to add 

```
 <Add-Opens>java.base/java.lang java.base/java.util</Add-Opens>
```

To the manifest for psi probe.  So it does the same thing as suggested but then only for psi probe.

**Comment by rw7** [comment]
I couldn't find any documentation about an `<Add-Opens>`. I just found [JEP 261](https://openjdk.org/jeps/261) talking about an `Add-Opens:` in jar manifests. And it says 

> These attributes are interpreted only in the main executable JAR file of an application, i.e., in the JAR file specified to the -jar option of the Java run-time launcher; they are ignored in all other JAR files.

So that would not work for any web application running in tomcat.

**Comment by hazendaz** [comment]
Are you able to make this xstream error even happen?  I'm using jdk 17 and have not seen that error at all even after dozens of restarts.  I get other issues during restarts around logback and quartz.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rw7** [comment]
It happened every time on our servers. That is Debian 11 bullseye with apt-get install openjdk-17-jdk-headless.
Here our list of jvm parameters, I don't think that one of it makes a difference:

```
-Dlog4j2.formatMsgNoLookups=true
-XX:+HeapDumpOnOutOfMemoryError
-XX:HeapDumpPath=/home/tomcatu/tomcat/log/jvm/
-XX:InitialCodeCacheSize=100M
-XX:ReservedCodeCacheSize=100M
-Djava.net.preferIPv4Stack=true
-Dcom.sun.management.jmxremote
-Djava.awt.headless=true
-Djava.security.egd=file:/dev/./urandom
-Dmail.mime.encodefilename=true
-Dmail.smtp.connectiontimeout=5000
-Dmail.smtp.timeout=5000
-Dwicket.configuration=deployment
-Dlog4j.configurationFile=/home/tomcatu/tomcat/conf/log4j.properties
-Dlog4j.configuration=file:/home/tomcatu/tomcat/conf/log4j.properties
-javaagent:/home/tomcatu/tomcat/jmx_prometheus_javaagent.jar=9404:/home/tomcatu/tomcat/conf/jmx_prometheus_javaagent.yml

```

**Comment by hazendaz** [comment]
@rw7 For now, I've applied what I was thinking for trapping the specific issue and applied to master.  I'm unable to verify this.  Nothing is failing for me btw.  It just always works.  Please retry master as the issue should be gone in your case now.

**Comment by hazendaz** [comment]
@rw7 ok I know why I don't have any issues now.  Tomcat actually defines add opens already.  So I'm guesing you are using jdk 17 and not on recent version of tomcat.  Tested at 9.0.52 and checked tomcat master on github which still has it as required for tomcat to run on jdk 9+.

current master shows...in catalina.sh

```
# Add the module start-up parameters required by Tomcat
JAVA_OPTS="$JAVA_OPTS --add-opens=java.base/java.lang=ALL-UNNAMED"
JAVA_OPTS="$JAVA_OPTS --add-opens=java.base/java.io=ALL-UNNAMED"
JAVA_OPTS="$JAVA_OPTS --add-opens=java.base/java.util=ALL-UNNAMED"
JAVA_OPTS="$JAVA_OPTS --add-opens=java.base/java.util.concurrent=ALL-UNNAMED"
JAVA_OPTS="$JAVA_OPTS --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"
```

I'm going to go ahead and close as this would indicate usage that is not compliant with tomcat and I added a patch that should be sufficient otherwise.  Please try the latest build here and you may want to double check your tomcat version / configuration.

**Pull request closed without merging**
