### PR TITLE
#Issue 659 Show TrustStore Certificates

### PR DESCRIPTION
**Pull request by sandrapascual**
Issue #659 Show TrustStore Certificates

### CODE REVIEW

**Comment by hazendaz** [comment]
Can you squash the commits?


Sent from Outlook Mobile






On Mon, Feb 8, 2016 at 5:41 AM -0800, "sandrapascual" <notifications@github.com> wrote:





#Issue 659 Show TrustStore Certificates
You can view, comment on, or merge this pull request online at:

  https://github.com/psi-probe/psi-probe/pull/660

-- Commit Summary --

  * Issue #659
  * Merge branch 'release/aa'
  * Merge branch 'master' into master

-- File Changes --

    A core/src/main/java/psiprobe/controllers/truststore/TrustStoreController.java (79)
    M web/src/main/webapp/WEB-INF/jsp/decorators/system.jsp (5)
    A web/src/main/webapp/WEB-INF/jsp/truststore.jsp (47)
    M web/src/main/webapp/WEB-INF/messages.properties (7)
    M web/src/main/webapp/WEB-INF/messages_es.properties (7)
    M web/src/main/webapp/WEB-INF/spring-probe-controllers.xml (4)

-- Patch Links --

https://github.com/psi-probe/psi-probe/pull/660.patch
https://github.com/psi-probe/psi-probe/pull/660.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/psi-probe/psi-probe/pull/660

**Comment by hazendaz** [comment]
@sandrapascual Please use our formatter when you rebase this as well and use slf4j to log the caught exception.  Thanks.

**Comment by hazendaz** [comment]
I tested this.  Currently this only works if using java parameters.   It doesn't work on tomcat connectors.  Do you happen to know how to get that working too?


Sent from Outlook Mobile






On Mon, Feb 8, 2016 at 5:41 AM -0800, "sandrapascual" <notifications@github.com> wrote:





#Issue 659 Show TrustStore Certificates
You can view, comment on, or merge this pull request online at:

  https://github.com/psi-probe/psi-probe/pull/660

-- Commit Summary --

  * Issue #659
  * Merge branch 'release/aa'
  * Merge branch 'master' into master

-- File Changes --

    A core/src/main/java/psiprobe/controllers/truststore/TrustStoreController.java (79)
    M web/src/main/webapp/WEB-INF/jsp/decorators/system.jsp (5)
    A web/src/main/webapp/WEB-INF/jsp/truststore.jsp (47)
    M web/src/main/webapp/WEB-INF/messages.properties (7)
    M web/src/main/webapp/WEB-INF/messages_es.properties (7)
    M web/src/main/webapp/WEB-INF/spring-probe-controllers.xml (4)

-- Patch Links --

https://github.com/psi-probe/psi-probe/pull/660.patch
https://github.com/psi-probe/psi-probe/pull/660.diff

---
Reply to this email directly or view it on GitHub:
https://github.com/psi-probe/psi-probe/pull/660

**Comment by sandrapascual** [comment]
Hi, I'm working on changing the caugth exception to slf4j and to squash the commits.
According to tomcat connectors, I thought it was a good option to get only the java parameters truststore so I put it on the system tab. 
Maybe we could merge this solution now (when I correct the previous errors you've mentioned) and I could think and find an option to include a new funcionality in connectors tab to obtain the trustore from server.xml. I'll work on it.
Thanks for your advices.

**Comment by sandrapascual** [comment]
Hi, 
I've tried to follow your advices but I'm having problems with Git. (I don't understand it a lot).
I tried to squash the commits and I've change the exception to use slf4j. Please, let me know if I have to change something more.
Sorry...

**Comment by hazendaz** [comment]
No worries.  Git is rather complicated.  I can see there are way more commits now...so


Here is what you need to do assuming you forked branch is also master.


git pull --rebase upstream master


That should flush out all commits we don't want to see leaving only your commits.  I'm not sure depending on how many are there no if you will run into merge conflicts.  What I can say if that I did this already on your code locally to test and it had zero merge conflicts.  If you get stuck I can push that up still giving you naming rights on the provided solution and noting so across your pull request and issue.  However let's see if you can get this!


After the rebase command let's assume you have 2 commits.  The original and adjustments I asked for.  Based on that you would do....


git rebase -i HEAD~2


Following directs git then provides you would squash you second commit with your first one.  Basically first commit would read as pick while second as squash.  Then save the file git opened.  Then git will show you another notepad with both original commits.  Just comment out the second one and again save.  This should then leave you just a single commit of your own.


Next and final step.


git push origin +master


That will force push your now rebased code to your master.  The pull request will stay intact and will now be what we want.  At that point back to our group to merge it.


Let me if this helps.



Sent from Outlook Mobile






On Tue, Feb 9, 2016 at 3:30 AM -0800, "sandrapascual" <notifications@github.com> wrote:





Hi,
I've tried to follow your advices but I'm having problems with Git. (I don't understand it a lot).
I tried to squash the commits and I've change the exception to use slf4j. Please, let me know if I have to change something more.
Sorry...

---

**Comment by sandrapascual** [comment]
Hi, I've not been able to solve the git problem so I've done a new pull request with only one commit with the solution.
Sorry for the inconvenience.

**Pull request closed without merging**
