### PR TITLE
[tomcat85] Add initial support for tomcat 8.5

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by afiller** [comment]
Hello, thank you for addressing Tomcat 8.5. Nevertheless it's not working on my installation:

`org.springframework.web.util.NestedServletException: Request processing failed; nested exception is java.lang.IllegalStateException: No container found for your server: Apache Tomcat/8.5.3 at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:979) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:858) at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:843) at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)`
...

...is the sad result.

Any ideas?

**My ideas:**

Maybe it has to do with the fact that I'm using the new functionality backported from Tomcat 9 to bind different hostnames to different webapp-paths using several <Host> attributes in server.xml

**What I did:**

* Building from source using MVN (current master)
* Also tried to adjust POM.xml for "Tomcat85" (instead of "Tomcat8") only

**Comment by hazendaz** [comment]
@afiller I found the issue.  I'll be patching the master shortly.  Once you see it patched, can you build a new copy and give it another try?

**Comment by afiller** [comment]
@hazendaz Yes, of course. I will report back ASAP.

**Comment by afiller** [comment]
Sadly there's still a problem. The full stack trace:

`javax.servlet.ServletException: Servlet.init() for servlet probe threw exception
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1210)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1110)
	at org.apache.catalina.core.StandardWrapper.allocate(StandardWrapper.java:790)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:702)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:469)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:394)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:311)
	at org.apache.jasper.runtime.PageContextImpl.doForward(PageContextImpl.java:742)
	at org.apache.jasper.runtime.PageContextImpl.forward(PageContextImpl.java:712)
	at org.apache.jsp.index_jsp._jspService(index_jsp.java:110)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:443)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:385)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:329)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:115)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:121)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:632)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'handlerMapping' defined in ServletContext resource [/WEB-INF/spring-probe-servlet.xml]: Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '/index.htm' defined in ServletContext resource [/WEB-INF/spring-probe-controllers.xml]: Cannot resolve reference to bean 'containerWrapper' while setting bean property 'containerWrapper'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'containerWrapper' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]: Cannot resolve reference to bean 'defaultResourceResolver' while setting bean property 'resourceResolvers' with key [TypedStringValue: value [default], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultResourceResolver' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]: Cannot create inner bean 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' of type [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] while setting bean property 'datasourceMappers' with key [5]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] for bean with name 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]; nested exception is java.lang.ClassNotFoundException: psiprobe.beans.Tomcat85DbcpDatasourceAccessor
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at psiprobe.ProbeServlet.init(ProbeServlet.java:65)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1194)
	... 59 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '/index.htm' defined in ServletContext resource [/WEB-INF/spring-probe-controllers.xml]: Cannot resolve reference to bean 'containerWrapper' while setting bean property 'containerWrapper'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'containerWrapper' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]: Cannot resolve reference to bean 'defaultResourceResolver' while setting bean property 'resourceResolvers' with key [TypedStringValue: value [default], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultResourceResolver' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]: Cannot create inner bean 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' of type [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] while setting bean property 'datasourceMappers' with key [5]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] for bean with name 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]; nested exception is java.lang.ClassNotFoundException: psiprobe.beans.Tomcat85DbcpDatasourceAccessor
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1076)
	at org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler(AbstractUrlHandlerMapping.java:326)
	at org.springframework.web.servlet.handler.AbstractUrlHandlerMapping.registerHandler(AbstractUrlHandlerMapping.java:305)
	at org.springframework.web.servlet.handler.AbstractDetectingUrlHandlerMapping.detectHandlers(AbstractDetectingUrlHandlerMapping.java:82)
	at org.springframework.web.servlet.handler.AbstractDetectingUrlHandlerMapping.initApplicationContext(AbstractDetectingUrlHandlerMapping.java:58)
	at org.springframework.context.support.ApplicationObjectSupport.initApplicationContext(ApplicationObjectSupport.java:120)
	at org.springframework.web.context.support.WebApplicationObjectSupport.initApplicationContext(WebApplicationObjectSupport.java:76)
	at org.springframework.context.support.ApplicationObjectSupport.setApplicationContext(ApplicationObjectSupport.java:74)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:121)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:97)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	... 76 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'containerWrapper' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]: Cannot resolve reference to bean 'defaultResourceResolver' while setting bean property 'resourceResolvers' with key [TypedStringValue: value [default], target type [null]]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultResourceResolver' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]: Cannot create inner bean 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' of type [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] while setting bean property 'datasourceMappers' with key [5]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] for bean with name 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]; nested exception is java.lang.ClassNotFoundException: psiprobe.beans.Tomcat85DbcpDatasourceAccessor
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedMap(BeanDefinitionValueResolver.java:407)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:165)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 98 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultResourceResolver' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]: Cannot create inner bean 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' of type [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] while setting bean property 'datasourceMappers' with key [5]; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] for bean with name 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]; nested exception is java.lang.ClassNotFoundException: psiprobe.beans.Tomcat85DbcpDatasourceAccessor
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveManagedList(BeanDefinitionValueResolver.java:382)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:157)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 110 more
Caused by: org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [psiprobe.beans.Tomcat85DbcpDatasourceAccessor] for bean with name 'psiprobe.beans.Tomcat85DbcpDatasourceAccessor#53301c1e' defined in ServletContext resource [/WEB-INF/spring-probe-resources.xml]; nested exception is java.lang.ClassNotFoundException: psiprobe.beans.Tomcat85DbcpDatasourceAccessor
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1357)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:455)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:299)
	... 122 more
Caused by: java.lang.ClassNotFoundException: psiprobe.beans.Tomcat85DbcpDatasourceAccessor
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1282)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1116)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.beans.factory.support.AbstractBeanDefinition.resolveBeanClass(AbstractBeanDefinition.java:394)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doResolveBeanClass(AbstractBeanFactory.java:1402)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1349)
	... 124 more`

**Comment by hazendaz** [comment]
ok - I got it fixed.  The 85 probe jar wasn't being included in the war.  I'll have that fixed shortly as well as officially tested it.  I was relying too much on Eclipse which doesn't yet support 8.5 ;)  Off to bash git now and was able to repeat all the issues as well as fix the problems.  I believe tomcat team is still treating 8.5 as beta at the moment but I presume it's getting much closer towards 8.0 full replacement.

**Comment by afiller** [comment]
Yeah, great! I can confirm as well that it works now. Thanks a lot! :-)

It's not showing the log files currently, but it's already great that I can update existing applications and see the system stats.

**Comment by hazendaz** [comment]
Great!  We are almost there.  What log files are you not seeing?  I know psi probe doesn't show everything and frankly I personally think we need to open up to just read off disk where we expect logs.  Currently it tries to find them in the classpath so there are certain logs that are not supported as a result (log4j2, logback-access, some tomcat logs, etc).  And grabbing off the classpath that way is a lot harder than expected.  I don't know enough in that area as I'm fairly new to supporting this but if you can help assist in what is missing I think I can make an attempt to make them visible.

**Pull request merged**
