### PR TITLE
Fix classloader Leak during JFreeChart initialization

### LINKED ISSUE #443: Classloader Leak during JFreeChart initialization
```
What steps will reproduce the problem?
1. Deploy probe.war
2. Access System - Memory Utilization (which starts JFreeChart)
3. Undeploy probe.war

What is the expected result?
A heap dump should not show probe classloader on the PermGen.


What happens instead?
The classloader of probe shows, which is stopped, does not get collected. See 
probeAppContextClassloaderLeak-01.png.


What version of Probe are you using?
2.3.3 and 2.4.0-SNAPSHOT

What environment (browser version, Tomcat version, JVM version, server OS)?
Chrome 40 64 bits, Tomcat 7.0.57, Java 1.7.0_60 64 bits (Oracle), Windows 7 64 
bits 

Please provide any additional information below.

The root cause can be viewed on probeAppContextClassloaderLeak-02.png

Add a patch solution as described at 
https://plumbr.eu/blog/hunting-down-memory-leaks-a-case-study

```

Original issue reported on code.google.com by `diogosan...@gmail.com` on 27 Jan 2015 at 5:37

Attachments:
* [probeAppContextClassloaderLeak-01.png](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/probeAppContextClassloaderLeak-01.png)
* [probeAppContextClassloaderLeak-02.png](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/probeAppContextClassloaderLeak-02.png)
* [psi-probe-patch.txt](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-443/comment-0/psi-probe-patch.txt)

### PR DESCRIPTION
**Pull request by diogosantana**
Fixed #443.

### CODE REVIEW

**Comment by MALfunction84** [comment]
Probe uses commons-logging, not slf4j. Can you correct this?

**Comment by jander99** [comment]
Are you wanting us to switch to use slf4j? Sounds like a 3.x thing.

**Comment by diogosantana** [comment]
Oh. Didn't want to do that. I will fix as soon as I get to a computer.
Today is soccer day, so it will take a while. :)
Em 23/04/2015 10:53, "Jeff Anderson" <notifications@github.com> escreveu:

**Comment by MALfunction84** [comment]
@jander99 This commit uses slf4j. I'd like @diogosantana to change it to commons-logging before I merge.

**Pull request closed without merging**
